nginx:
 image: nginx:latest
 volumes:   
   - /tmp/nginx:/etc/nginx/conf.d
   - ./web/static/:/data/static #static data paths
    #https certs here
 volumes_from:
   - web1
   - web2
 ports:
   - "80:80"
   #- "443:443" #https
 links:
   - web1
   - web2

dockergen:
  image: jwilder/docker-gen:latest
  links:
   - nginx
  volumes_from:
   - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /master/extra:/etc/docker-gen/templates
  tty: true
  entrypoint: ["/bin/sh", "-c"]
  command: >
    "
    docker-gen
    -watch
    -only-exposed
    -notify-sighup $(echo $NGINX_NAME | tail -c +2)
    /etc/docker-gen/templates/nginx.tmpl
    /etc/nginx/conf.d/default.conf
    "

web1:
 restart: always
 build: ./web
 environment:
  VIRTUAL_HOST: loc.termsheet.io
 ports:
  - "8000"
 command: python /code/manage.py runserver 0.0.0.0:8000
 links:
 - db
 - redis
 #- elasticsearch

web2:
 restart: always
 build: ./web
 environment:
  VIRTUAL_HOST: loc.termsheet.io
 ports:
  - "8000"
 command: python /code/manage.py runserver 0.0.0.0:8000
 links:
 - db
 - redis
 #- elasticsearch

db:
 restart: always
 image: postgres:latest
 ports: 
  - "5432"
 volumes_from:
  - dbdata

dbdata:
  restart: always
  image: library/postgres:latest
  volumes:
   - /var/lib/postgresql/data/
   - /var/run/postgresql/

redis:
  image: redis:latest
  ports:
   - "6379"
  volumes_from:
   - redisdata

redisdata:
  image: redis:latest
  volumes:
   - /var/lib/redisdata/data


